/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleados;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        Inicio = new button.button();
        Empleados = new button.button();
        Departamentos = new button.button();
        btnUsuarios = new button.button();
        jLabel4 = new javax.swing.JLabel();
        Concepto = new button.button();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnDetalle = new button.button();
        NominaEncabezado = new button.button();
        Bancos = new button.button();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salir = new button.button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio.setBackground(new java.awt.Color(240, 240, 240));
        Inicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Inicio.setForeground(new java.awt.Color(153, 153, 153));
        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa (1).png"))); // NOI18N
        Inicio.setText("  INICIO");
        Inicio.setBorderPainted(false);
        Inicio.setColorBorde(null);
        Inicio.setColorHover(new java.awt.Color(153, 204, 0));
        Inicio.setColorNormal(new java.awt.Color(240, 240, 240));
        Inicio.setColorPressed(new java.awt.Color(153, 204, 0));
        Inicio.setColorTextHover(new java.awt.Color(0, 0, 0));
        Inicio.setColorTextNormal(new java.awt.Color(153, 153, 153));
        Inicio.setColorTextPressed(new java.awt.Color(0, 0, 0));
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        Menu.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 50, 260, 70));

        Empleados.setBackground(new java.awt.Color(240, 240, 240));
        Empleados.setForeground(new java.awt.Color(153, 153, 153));
        Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trabajo-en-equipo.png"))); // NOI18N
        Empleados.setText("EMPLEADOS");
        Empleados.setBorderPainted(false);
        Empleados.setColorHover(new java.awt.Color(153, 204, 0));
        Empleados.setColorNormal(new java.awt.Color(240, 240, 240));
        Empleados.setColorPressed(new java.awt.Color(153, 204, 0));
        Empleados.setColorTextHover(new java.awt.Color(0, 0, 0));
        Empleados.setColorTextNormal(new java.awt.Color(153, 153, 153));
        Empleados.setColorTextPressed(new java.awt.Color(0, 0, 0));
        Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosActionPerformed(evt);
            }
        });
        Menu.add(Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 230, 260, 80));

        Departamentos.setBackground(new java.awt.Color(240, 240, 240));
        Departamentos.setForeground(new java.awt.Color(153, 153, 153));
        Departamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colaboracion.png"))); // NOI18N
        Departamentos.setText("DEPARTAMENTOS");
        Departamentos.setBorderPainted(false);
        Departamentos.setColorHover(new java.awt.Color(153, 204, 0));
        Departamentos.setColorNormal(new java.awt.Color(240, 240, 240));
        Departamentos.setColorPressed(new java.awt.Color(153, 204, 0));
        Departamentos.setColorTextHover(new java.awt.Color(0, 0, 0));
        Departamentos.setColorTextNormal(new java.awt.Color(153, 153, 153));
        Departamentos.setColorTextPressed(new java.awt.Color(0, 0, 0));
        Departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentosActionPerformed(evt);
            }
        });
        Menu.add(Departamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, 70));

        btnUsuarios.setBackground(new java.awt.Color(240, 240, 240));
        btnUsuarios.setForeground(new java.awt.Color(153, 153, 153));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/equipo.png"))); // NOI18N
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setColorHover(new java.awt.Color(153, 204, 0));
        btnUsuarios.setColorNormal(new java.awt.Color(240, 240, 240));
        btnUsuarios.setColorPressed(new java.awt.Color(153, 204, 0));
        btnUsuarios.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnUsuarios.setColorTextNormal(new java.awt.Color(153, 153, 153));
        btnUsuarios.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        Menu.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 120, 260, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("            SUBMENÚ");
        Menu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 30));

        Concepto.setBackground(new java.awt.Color(240, 240, 240));
        Concepto.setForeground(new java.awt.Color(153, 153, 153));
        Concepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dinero.png"))); // NOI18N
        Concepto.setText("CONCEPTO");
        Concepto.setBorderPainted(false);
        Concepto.setColorHover(new java.awt.Color(153, 204, 0));
        Concepto.setColorNormal(new java.awt.Color(240, 240, 240));
        Concepto.setColorPressed(new java.awt.Color(153, 204, 0));
        Concepto.setColorTextHover(new java.awt.Color(0, 0, 0));
        Concepto.setColorTextNormal(new java.awt.Color(153, 153, 153));
        Concepto.setColorTextPressed(new java.awt.Color(0, 0, 0));
        Concepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConceptoActionPerformed(evt);
            }
        });
        Menu.add(Concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 390, 270, 70));

        jPanel3.setBackground(new java.awt.Color(153, 204, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("                 MENÚ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        Menu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        btnDetalle.setBackground(new java.awt.Color(240, 240, 240));
        btnDetalle.setForeground(new java.awt.Color(153, 153, 153));
        btnDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/oficina.png"))); // NOI18N
        btnDetalle.setText("DETALLE");
        btnDetalle.setBorderPainted(false);
        btnDetalle.setColorHover(new java.awt.Color(153, 204, 0));
        btnDetalle.setColorNormal(new java.awt.Color(240, 240, 240));
        btnDetalle.setColorPressed(new java.awt.Color(153, 204, 0));
        btnDetalle.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnDetalle.setColorTextNormal(new java.awt.Color(153, 153, 153));
        btnDetalle.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleActionPerformed(evt);
            }
        });
        Menu.add(btnDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 460, 280, 70));

        NominaEncabezado.setBackground(new java.awt.Color(240, 240, 240));
        NominaEncabezado.setForeground(new java.awt.Color(153, 153, 153));
        NominaEncabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario.png"))); // NOI18N
        NominaEncabezado.setText("N. ENCABEZADO");
        NominaEncabezado.setBorderPainted(false);
        NominaEncabezado.setColorHover(new java.awt.Color(153, 204, 0));
        NominaEncabezado.setColorNormal(new java.awt.Color(240, 240, 240));
        NominaEncabezado.setColorPressed(new java.awt.Color(153, 153, 153));
        NominaEncabezado.setColorTextHover(new java.awt.Color(0, 0, 0));
        NominaEncabezado.setColorTextNormal(new java.awt.Color(153, 153, 153));
        NominaEncabezado.setColorTextPressed(new java.awt.Color(0, 0, 0));
        NominaEncabezado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NominaEncabezadoActionPerformed(evt);
            }
        });
        Menu.add(NominaEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 220, 70));

        Bancos.setBackground(new java.awt.Color(240, 240, 240));
        Bancos.setForeground(new java.awt.Color(153, 153, 153));
        Bancos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolsa-de-dinero.png"))); // NOI18N
        Bancos.setText("BANCOS");
        Bancos.setBorderPainted(false);
        Bancos.setColorHover(new java.awt.Color(153, 204, 0));
        Bancos.setColorNormal(new java.awt.Color(240, 240, 240));
        Bancos.setColorPressed(new java.awt.Color(153, 204, 0));
        Bancos.setColorTextHover(new java.awt.Color(0, 0, 0));
        Bancos.setColorTextNormal(new java.awt.Color(153, 153, 153));
        Bancos.setColorTextPressed(new java.awt.Color(0, 0, 0));
        Bancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BancosActionPerformed(evt);
            }
        });
        Menu.add(Bancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 600, 270, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLANILLA EMPLEADOS");

        salir.setBackground(new java.awt.Color(240, 240, 240));
        salir.setForeground(new java.awt.Color(153, 153, 153));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png"))); // NOI18N
        salir.setText("  SALIR");
        salir.setBorderPainted(false);
        salir.setColorHover(new java.awt.Color(153, 204, 0));
        salir.setColorNormal(new java.awt.Color(240, 240, 240));
        salir.setColorPressed(new java.awt.Color(153, 153, 153));
        salir.setColorTextHover(new java.awt.Color(0, 0, 0));
        salir.setColorTextNormal(new java.awt.Color(153, 153, 153));
        salir.setColorTextPressed(new java.awt.Color(0, 0, 0));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap(284, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        try{
            JOptionPane.showMessageDialog( null,"Estas seguro de salir del programa");
             System.exit(0);
           }catch(Exception e){
            JOptionPane.showMessageDialog( null,"Ha ocurrido un error no se puede salir");
        }
    }//GEN-LAST:event_salirActionPerformed

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
       // intro ver = new intro();
       // ver.setVisible(true);
    }//GEN-LAST:event_InicioActionPerformed

    private void EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosActionPerformed

        Empleados ver = new Empleados();
           ver.setVisible(true);  
    }//GEN-LAST:event_EmpleadosActionPerformed

    private void ConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConceptoActionPerformed
        Concepto ver = new Concepto();
        ver.setVisible(true);
    }//GEN-LAST:event_ConceptoActionPerformed

    private void DepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentosActionPerformed
  Departamentos ver=new Departamentos();
                ver.setVisible(true);    
    }//GEN-LAST:event_DepartamentosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
       Usuarios ver=new Usuarios();
                ver.setVisible(true);        
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleActionPerformed
              Detalle ver=new Detalle();
                ver.setVisible(true);    
    }//GEN-LAST:event_btnDetalleActionPerformed

    private void NominaEncabezadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NominaEncabezadoActionPerformed
 Encabezado ver=new Encabezado();
                ver.setVisible(true);   
    }//GEN-LAST:event_NominaEncabezadoActionPerformed

    private void BancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BancosActionPerformed
        Bancos ver=new Bancos();
                ver.setVisible(true);    
    }//GEN-LAST:event_BancosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.button Bancos;
    private button.button Concepto;
    private button.button Departamentos;
    private button.button Empleados;
    private button.button Inicio;
    private javax.swing.JPanel Menu;
    private button.button NominaEncabezado;
    private button.button btnDetalle;
    private button.button btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private button.button salir;
    // End of variables declaration//GEN-END:variables
}
